name: quickbooks
description: Implementation of the Quickbook API in Dart. Basic functionalities include ; OAuth2 authentication, SQL Query for quickbooks Online and basic class mapping. 
version: 0.0.4
homepage: https://github.com/apollocode-ca/dart-quickbooks

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# To format according to the dartfmt : dartfmt -w .

# The following section is specific to Flutter.
flutter:

